### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by AdamYLiang** [gkopplin/grumblr#1]
- [x] Try to limit user auth to be 1-2 days
- [x] Have follows as a main MVP, consider making search a bonus MVP

Let me know if you have any questions or more details!

**Comment by gkopplin** [comment]
I don't think I'll be able to create a polished splash page with animations (on top of auth) in 2 days. I might need to start with a static page and add animations later if I have time. Slack me if there's any issues with that. Thanks!

**Comment by AdamYLiang** [comment]
I think you can make it, we'll see when the time comes!
