### ISSUE TITLE
Frontend/Backend Routes

### ISSUE THREAD

**Issue by AdamYLiang** [gkopplin/grumblr#4]
### Backend Routes
- [x] Have a route to get follows information 

Everything else looks good. Let me know if you have any questions!

**Comment by gkopplin** [comment]
Let me know if that route looks alright. Thanks!

**Comment by AdamYLiang** [comment]
Might want to have a POST route as well and then it should be good.

**Comment by gkopplin** [comment]
Right, that makes sense. Just added!
