### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by gkopplin** [gkopplin/grumblr#5]
## Auth

- [x] MVP is bug free with smooth navigation
- [x] MVP is bug free on a hard refresh (⌘ + R)
- [x] New users can register
- [x] Existing users can sign in
- [x] Log-in status affects which pages are shown
- [x] Splash page complete
- [x] Nav bar with drop down menu complete

### Additional Notes:
To do:
* Finish styling and add seed data
* Handle errors

**Comment by AdamYLiang** [comment]
- [ ] Error handling for wrong input
Everything else looks great!

**Comment by gkopplin** [comment]
Done with errors and demo user! I'm going to work on styling a little bit more, but hope to focus mainly on the next MVP. There's a lot of little styling things to tweak, so let me know your thoughts.

**Comment by gkopplin** [comment]
Thanks for your help Adam! I made those changes and pushed to Heroku. Let me know if you have any other suggestions for this MVP

**Comment by AdamYLiang** [comment]
- [ ] Login on no fields leads to error page 
- [ ] CSS styling on dropdown

**Comment by AdamYLiang** [comment]
- [ ] Signup/Login input fields and button should be extended 
- [ ] White button background for `login/signup` in corner
- [ ] Change color on dashboard and navbar to match the real site
- [ ] Extend the length of the dropdown menu in dashboard

When you are done with modals and other MVPs feel free to come back and make the email transition on login.

**Comment by AdamYLiang** [comment]
- [ ] Demo user seems to not be working
- [ ] Buttons should be slightly larger and solid color
