### ISSUE TITLE
Posts

### ISSUE THREAD

**Issue by gkopplin** [gkopplin/grumblr#6]
## Posts

- [x] MVP is completely styled and seeded
- [x] MVP is bug free with smooth navigation
- [x] MVP is bug free on a hard refresh (⌘ + R)
- [x] MVP handles errors with informative messages for user
- [x] When logged in, users can create, edit, and delete their own posts

### Additional Notes:
Right now I am displaying all posts on the dashboard, but for the next MVP, I'll fix that

**Comment by AdamYLiang** [comment]
- [ ] Settings button mispositioned at times 
- [ ] Settings button should disappear if they click out 
- [ ] Posts should persist on refreshes 
- [ ] General CSS to match real site

**Comment by gkopplin** [comment]
Alright, these issues should be all set now. Let me know if I missed any CSS stuff. The splash page looks really bad without transparency, but if you feel strongly about it, I can try to find another background image

**Comment by gkopplin** [comment]
I just realized I missed a couple buttons that I was going to resize. I'll fix that tomorrow morning!

**Comment by gkopplin** [comment]
Ok buttons should be good now. Let me know if I missed anything else! (In the code I just pushed there is a search bar at the top, but I am still working on that feature)
